.github/workflows/ci.yaml
src/charm.py
tests/integration/helpers.py
tests/integration/test_charm.py
tests/integration/test_kafka_provider.py

Update the integration tests with k8s related changes.
- Using `resources` to add the container
- Add blocking calls for zookeeper (deploys with 3 units)

Fix integration tests

---

actions.yaml
pyproject.toml
src/charm.py
src/literals.py
src/utils.py
tests/integration/helpers.py
tests/integration/test_password_rotation.py

This PR adds an action to change the password of an operator related user.
The charm sends the user change to zookeeper and then stores the new password on the application databag.
- Added actions to set passwords.
- `charm.py`:
- Added password rotation action handler
- Added some extra helpers for integration tests.
Added an integration test for password rotation.

Add password rotation logic

---

tests/unit/test_config.py

While playing around with the repo, I noticed that unittests were failing because of a small mismatch

[MISC] Fix unittests

---

actions.yaml
charmcraft.yaml
requirements.txt
src/auth.py
src/charm.py
src/config.py
src/literals.py
src/provider.py
src/tls.py
src/utils.py
tests/integration/helpers.py
tests/integration/test_tls.py
tests/unit/test_config.py
tox.ini

This PR partially addresses Jira ticket [DPE-657](https://warthogs.atlassian.net/browse/DPE-657).
Adds initial TLS implementation to Kafka.
**This PR is almost the same as [kafka-vm TLS](https://github.com/canonical/kafka-operator/pull/23). Only significant changes are**:
- How files are pushed to the container
- The command that gets executed to create keystore/truststore
**Implementation is being tested against https://github.com/canonical/zookeeper-k8s-operator/pull/16**
The relation with `tls-certificates-operator` is used to obtain the certificates. At the moment, the setup is configured to share the same CA as zookeeper. Both Kafka and Zookeeper need to have TLS relation for the shared mechanism to work. (In the future this will be decoupled so Zookeeper shares ca information …

TLS implementation

---

src/charm.py
src/config.py
src/provider.py
tests/integration/helpers.py
tests/integration/test_provider.py

This PR addresses Jira ticket [DPE-661](https://warthogs.atlassian.net/browse/DPE-661).
Updates relation info on peer-related events.
Adds a call on `config_changed` event that updates related application info, if they exist.
- `src/charm.py`: _on_config_changed_ now updates provider info.
- `src/config.py`: _bootstrap_server_ will change the port depending on TLS status.
- `src/provider.py`: added a method to update information on related applications.
Added a test on the provider-suite to check connection information.

fix: Update relation endpoints

---

src/charm.py
src/config.py

Linked to Jira [DPE-660](https://warthogs.atlassian.net/browse/DPE-660).
Changes `sync_password` to be stored using the `set_secret`/`get_secret` placeholders.
Note: Information coming from Zookeeper relation is not stored using the same scheme.

chore: Password to use secret placeholders

---

requirements.txt
src/auth.py
src/charm.py
src/config.py
src/literals.py
src/provider.py
src/utils.py
tests/unit/helpers.py
tests/unit/test_auth.py
tests/unit/test_charm.py
tests/unit/test_config.py
tests/unit/test_provider.py
tox.ini

- Use `CONTAINER` literal, set `CHARM_KEY` to `kafka-k8s`
- Append `--zk-tls-config-file` flag to bin commands
- Numerous type-hint warnings
- Remove references to `snap` left-over from VM charms
- Use `sync-password` instead of underscored equivalent

test: use pytest unittests

---

pyproject.toml
src/auth.py
src/charm.py
src/config.py
src/provider.py
src/tls.py
tests/integration/helpers.py
tests/integration/test_scaling.py
tests/unit/test_auth.py
tests/unit/test_config.py

Specifies source directories for ruff so imports are split following Python patterns.

Fix ruff import sorting

---

README.md
lib/charms/grafana_k8s/v0/grafana_dashboard.py
lib/charms/loki_k8s/v0/loki_push_api.py
lib/charms/observability_libs/v0/juju_topology.py
lib/charms/prometheus_k8s/v0/prometheus_scrape.py
metadata.yaml
src/charm.py
src/config.py
src/grafana_dashboards/kafka-metrics.json
src/literals.py
src/provider.py
tests/integration/test_charm.py
tests/unit/test_config.py

Addresses [DPE-1237](https://warthogs.atlassian.net/browse/DPE-1237)
The PR switches to using [`charmed/kafka`](https://hub.docker.com/r/charmed/kafka) OCI. Key aspects of this switch:
- OCI image now pulls from the `charmed-kafka` snap.
- Integrates JMX exporter into the image, adding it at startup on port 9101.
- Logging integration with Loki.
- Commit [that adds lilbs](https://github.com/canonical/kafka-k8s-operator/commit/078a91cc3c7704ccb9f3d86ef8d8702d5d7c440a) can be omitted from review.
To test, follow documentation added in the README
[DPE-1237]: https://warthogs.atlassian.net/browse/DPE-1237?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feature: exporter integration

---

metadata.yaml

Closes: [DPE-1561](https://warthogs.atlassian.net/browse/DPE-1561)
Docker is sun-setting Free Team organizations, including https://hub.docker.com/r/charmed
Moving to GitHub Container Registry (ghcr.io). OCI Tags are described [here](https://warthogs.atlassian.net/browse/DPE-1502?focusedCommentId=209163).
[DPE-1561]: https://warthogs.atlassian.net/browse/DPE-1561?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Move charmed-kafka OCI from DockerHub to GitHub Container Registry

---

.github/workflows/ci.yaml
.github/workflows/release.yaml

Otherwise the old action ignores ghcr.io registry and failing:
> Run canonical/charming-actions/upload-charm@2.1.0
> /usr/bin/sudo snap install charmcraft --classic --channel latest/stable
> charmcraft 2.2.0 from Canonical** installed
> /usr/bin/sudo charmcraft pack --destructive-mode --quiet
> /usr/bin/docker pull ghcr.io/canonical/charmed-kafka:3.3.2-22.04_edge
> 3.3.2-22.04_edge: Pulling from canonical/charmed-kafka
> 74ac377868f8: Pulling fs layer
> 59df4c571eb5: Pulling fs layer
> fcebd5cdc2a9: Pulling fs layer
> fcebd5cdc2a9: Verifying Checksum
> fcebd5cdc2a9: Download complete
> 74ac377868f8: Verifying Checksum
> 74ac377868f8: Download complete
> 74ac377868f8: Pull complete
> 59df4c571eb5: Verifying Checksum
> 59df4c571eb5: Download complete
> 59df4c571eb5: Pull complete
> …

Update GH Actions to the latest version

---

src/provider.py
tests/unit/test_provider.py

This PR solves an issue related to the first relation with the `kafka_client` interface. 
The relation implies the enabling of the client listener (that requires a restart), the restart need to be done before sending the credentials in the `topic_requested` event.

Fix relation provider for Kafka-k8s charm

---

src/tls.py

This PR reintroduce the check in the certificate available event. CI is really slow and need the container is not ready in time for the event.

Reintroduce check for container ready

---

actions.yaml
src/charm.py

`refactor: remove rolling-restart-units action`
- This action was originally added by request of customer teams needing an easy way of applying manual additions to features not yet provided in the base charm, in a safe rolling way
- Since then, a lot of those features have been brought into the core charm, rendering this action redundant
- The description of the method was somewhat confusing, with it's actual usage not being clear
- It also likely does not work as expected since the refactoring of the `_restart()` method no longer rolling itself but instead always restarting the service
- We can add this method back when we commit to supporting Juju 3.X, where the syntax will be clearer:
```bash
juju run-action rolling-restart-unit kafka/0
juju run-action rolling-restart-unit kafka/1
juju …
```

chore: remove rolling-restart action

---

metadata.yaml

Addressing https://warthogs.atlassian.net/browse/DPE-1901
We want to bind each charm (Zookeeper, Kafka) on both substrate (K8s, VM) with pinned snap revision and rocks hashes.
Take inspiration from mysql 
* [VM](https://github.com/canonical/mysql-operator/blob/main/src/constants.py#L27)
* [K8s](https://github.com/canonical/mysql-k8s-operator/blob/main/metadata.yaml#L36)
All charms are pinned to snap revision and rock hashes

[DPE-1901] Bind pinned image revision

---

src/grafana_dashboards/kafka-metrics.json

Both kafka and kafka-k8s charms include a grafana dashboard which uses a variable $job.
This variable does not seem to add value to the monitoring capability, as it is both redundant with other filters (namely juju-model), and not configured to enable multi selection (which causes issues when we deploy a vm cluster and a k8s cluster related to the same monitoring stack).

[DPE-3880] Remove all instances of  variable $job in dashboard

---

.github/workflows/ci.yaml
.github/workflows/release.yaml
tox.ini

There are a couple of improvements to the CI, such that the checks are clean, even for external contributors
* Disabling sync docs from contribution outside of Canonical
* Disabling security checks which is not the standard in DP anymore
* Disabling the lib-check which should not be part of CI, but a scheduled run

[MISC] CI improvements

---

lib/charms/hydra/v0/oauth.py
metadata.yaml
src/charm.py
src/core/cluster.py
src/core/models.py
src/events/oauth.py
src/literals.py
src/managers/config.py
tests/integration/helpers.py
tests/integration/test_charm.py
tests/integration/test_tls.py
tests/unit/test_config.py

This PR adds an sasl/oauthbearer listener to the Kafka (based on the Strimzi implementation).
This listener is added as a response to kafka beying related to hydra (or oauth-external-idp-integrator)

Add Oauth config from the oauth interface

---

actions.yaml
src/events/balancer.py
src/literals.py
src/managers/balancer.py
tests/integration/test_balancer.py
tests/integration/test_provider.py
tests/integration/test_tls.py
tests/unit/test_balancer.py

This PR adds a new param to the rebalance action to pass broker ids to be added/removed to/from the cluster.
This parameter can be used as follows:
```bash
juju run kafka-k8s/leader rebalance mode=remove dryrun=false brokerid=4
```
If we pass multiple brokers to remove to CC REST API, but all of them cannot be removed within the goals defined, Cruise Control will still move partition from some of the brokers.  This means we need to assess the cluster state before removing units.
The charm limits the rebalance action to add/remove one unit at a time

[DPE-4952] Add add/remove broker capability to rebalance action

---

src/managers/config.py
tests/integration/test_charm.py

- Fixes https://github.com/canonical/kafka-operator/issues/230
- ZooKeeper ACLs are not recursive, meaning that any written data to a zNode nested under the `chroot`, will be readable by all
- Setting`zookeeper.set.acl=true` ensures that there are protections on the zNodes written by Kafka

[DPE-5208] - fix: secure written znodes

---

config.yaml
src/core/cluster.py
src/core/models.py
src/core/structured_config.py
tests/integration/ha/test_ha.py
tests/integration/test_balancer.py
tests/integration/test_charm.py
tests/integration/test_password_rotation.py
tests/integration/test_provider.py
tests/integration/test_scaling.py
tests/integration/test_tls.py
tests/unit/conftest.py
tests/unit/scenario/test_balancer.py
tests/unit/test_charm.py
tests/unit/test_config.py
tests/unit/test_provider.py
tests/unit/test_tls.py
tests/unit/test_upgrade.py

- Overview of the various NodePort services that can be created
- Short guide on how to enable NodePort access
- Quick overview of making client connections through a `bootstrap` service with Kafka generally
- Docs didn't include OAUTHBEARER feature
- Changed the use of EXTERNAL to mean 'k8s-external', with CLIENT being the new 'k8s-internal, but not internal to the charm'
- Have set `expose-external=nodeport` in all our integration tests, as they will test the nodeport feature implicitly when making client connections between apps
- This was probably not tested sufficiently before, is present now in existing listener test

[DPE-5262] - docs: add External K8s connection how-to

---

charmcraft.yaml
config.yaml
poetry.lock
pyproject.toml
src/core/structured_config.py
tests/integration/ha/test_ha.py
tests/integration/test_balancer.py
tests/integration/test_charm.py
tests/integration/test_password_rotation.py
tests/integration/test_provider.py
tests/integration/test_scaling.py
tests/integration/test_tls.py
tests/unit/test_config.py

This PR rename the 'expose-external' configuration option to 'expose_external' (with an underscore) for consistency with the other options.
In addition, we upgrade the rust toolchain to get rid of the version constraint on `rdps-py`.

[DPE-5945] Rename expose_external configuration option

---

.github/workflows/ci.yaml
actions.yaml
config.yaml
metadata.yaml
src/charm.py
src/core/cluster.py
src/core/models.py
src/core/structured_config.py
src/events/actions.py
src/events/balancer.py
src/events/broker.py
src/events/peer_cluster.py
src/events/tls.py
src/literals.py
src/managers/auth.py
src/managers/balancer.py
src/managers/config.py
src/managers/tls.py
src/workload.py
tests/integration/test_kraft.py
tests/unit/test_charm.py
tests/unit/test_config.py
tests/unit/test_kraft.py
tests/unit/test_structured_config.py
tests/unit/test_tls.py
tests/unit/test_upgrade.py
tox.ini

- Features are as found in the VM charm at point of writing
- This also required `refactor: remove broker.host, use internal_address/node_ip`, as `broker.host` was erroneously resolving to the nodeip for the unit when configuring `controller.quorum.listeners`, which Kafka can't bind to
- Before, this was a K8s only feature, minor tweaks to make compatible with VMs also

[DPE-6011] - feat: reconcile vm+k8s feature drift

---

src/core/cluster.py
src/events/tls.py
src/managers/tls.py
tests/integration/helpers.py
tests/integration/test_tls.py

- Added **truststore dynamic reload** functionality using `kafka-configs` utility to reload truststore without broker restart
- Added integration test for truststore dynamic reload functionality

[DPE-5553] feat: Don't restart server on keystore/truststore updates

---

src/core/models.py
src/events/upgrade.py
src/events/zookeeper.py
tests/integration/helpers.py
tests/integration/test_balancer.py
tests/integration/test_kraft.py
tests/integration/test_tls.py
tests/integration/test_upgrade.py
tests/unit/test_config.py

- Resolved by adding backwards compatibility fix

fix: failing upgrades without chain

---

src/core/models.py
tests/integration/test_kraft.py

This PR fixes a `RelationDataAccessError` bug occurred in KRaft multi-mode on broker side during scale-out. 
-  KRaft multi-mode, broker-side scale-out results in error state.

 [DPE-6547] fix: KRaft multi-mode scaling bug on broker side

---

poetry.lock
pyproject.toml
src/core/workload.py
src/events/broker.py
src/events/provider.py
src/literals.py
src/managers/controller.py
src/managers/tls.py
src/workload.py
tests/integration/test_balancer.py
tests/integration/test_charm.py
tests/integration/test_kraft.py
tests/integration/test_tls.py
tests/unit/conftest.py
tests/unit/test_config.py

Ports https://github.com/canonical/kafka-operator/pull/334

[DPE-6436] fix: use pathops for proper cleanup of TLS artifacts

---

actions.yaml
config.yaml
src/core/structured_config.py
src/events/actions.py
src/events/broker.py
src/events/user_secrets.py
src/managers/config.py
tests/integration/helpers.py
tests/integration/test_password_rotation.py
tests/unit/test_user_secrets.py

This PR adds support for secret-based user management, compliant to DA146, and removes get/set-password actions.
- Adds `system-users` config option
- Adds `user_secrets` event handler
- Removes `set-password` and `get-user-credentials` actions

[DPE-7284] feat: add support for secret-based user management

---

docs/conf.py
docs/explanation/security.md
docs/redirects.txt
docs/requirements.txt

Implementing page-to-page matching to apply after wildcard redirects.
You can check them by navigating to the preview build URLs:
Test 1:
https://canonical-ubuntu-documentation-library--213.com.readthedocs.build/charmed-kafka-k8s/213/t-relate-kafka/
should redirect to
https://canonical-ubuntu-documentation-library--213.com.readthedocs.build/charmed-kafka-k8s/213/tutorial/integrate-with-client-applications/index.html
Test 2:
https://canonical-ubuntu-documentation-library--213.com.readthedocs.build/charmed-kafka-k8s/213/h-deploy-aks/
should redirect to
https://canonical-ubuntu-documentation-library--213.com.readthedocs.build/charmed-kafka-k8s/213/how-to/deploy/deploy-aks/index.html

Implement page-to-page Discourse redirects
