canonical/kafka-k8s-operator

lib/charms/prometheus_k8s/v0/prometheus_scrape.py

Update prometheus_scrape to version 0.17 as 0.16 had a critical bug https://github.com/canonical/prometheus-k8s-operator/issues/238

update prometheus_scrape library

---

charmcraft.yaml
lib/charms/tls_certificates_interface/v1/tls_certificates.py
lib/charms/zookeeper/v0/client.py
metadata.yaml
requirements.txt

Nothing to review. This just updates `zookeeper` lib, and adds `tls_certificates_interface` to the repo.

Add and update needed libs to project

---

actions.yaml
charmcraft.yaml
lib/charms/tls_certificates_interface/v1/tls_certificates.py
lib/charms/zookeeper/v0/client.py
metadata.yaml
requirements.txt
src/auth.py
src/charm.py
src/config.py
src/literals.py
src/provider.py
src/tls.py
src/utils.py
tests/integration/helpers.py
tests/integration/test_tls.py
tests/unit/test_config.py
tox.ini

Merge reviewed branch into main.

feat: TLS encryption support

---

.github/workflows/ci.yaml
.github/workflows/release.yaml
tests/integration/test_password_rotation.py
tests/integration/test_provider.py
tests/integration/test_scaling.py
tox.ini

Splits integration tests on the CI/CD pipelines

chore: Split integration tests

---

README.md
config.yaml
metadata.yaml

Addresses [DPE-1010](https://warthogs.atlassian.net/browse/DPE-1010).
Change docs to follow current readme scheme. 
[DPE-1010]: https://warthogs.atlassian.net/browse/DPE-1010?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Improve readme

---

lib/charms/data_platform_libs/v0/data_interfaces.py
lib/charms/grafana_k8s/v0/grafana_dashboard.py
lib/charms/loki_k8s/v0/loki_push_api.py
src/provider.py
tests/integration/app-charm/lib/charms/data_platform_libs/v0/data_interfaces.py
tests/integration/app-charm/src/charm.py
tests/integration/helpers.py
tests/integration/test_provider.py
tests/unit/test_provider.py

Importing this feature from the kafka-operator charm in order to have data-integrator tests stable in this [PR](https://github.com/canonical/data-integrator/pull/18)

Set of consumer-prefix-group from relation data

---

lib/charms/data_platform_libs/v0/data_interfaces.py
lib/charms/data_platform_libs/v0/data_models.py
lib/charms/grafana_k8s/v0/grafana_dashboard.py
lib/charms/loki_k8s/v0/loki_push_api.py
lib/charms/prometheus_k8s/v0/prometheus_scrape.py

Updating libraries to most recent versions

[MISC] Update charm libs

---

src/alert_rules/prometheus/kafka_metrics.rules
src/charm.py
src/grafana_dashboards/kafka-metrics.json
src/literals.py

Backporting the alert rules and dashboard we have in VM to K8s. 
I have tested every single rule to make sure they are working, and dashboard to make sure they were reasonably populated

[DPE-2331] Backport dashboards and alerting rules from vm to k8s

---

config.yaml
src/structured_config.py
src/tls.py
tests/unit/test_tls.py

Ported from https://github.com/canonical/kafka-operator/pull/125

[DPE-2195] Add `extra_sans` config option

---

tests/integration/ha/ha_helpers.py
tests/integration/ha/test_ha.py

[DPE-2642] Pod rescheduling test

---

.github/workflows/release.yaml
.github/workflows/sync_issue_to_jira.yaml
tests/integration/ha/test_ha.py

chore: update version of actions

---

tests/integration/test_tls.py

Copy pasta of https://github.com/canonical/kafka-operator/pull/188

[DPE-3333] Add integration test for broken tls

---

src/charm.py
src/core/workload.py
src/literals.py
src/managers/config.py
tests/integration/helpers.py
tests/integration/test_balancer.py
tests/unit/test_config.py

See https://github.com/canonical/kafka-operator/pull/215

COS Integration for Cruise Control

---

src/charm.py
src/core/workload.py
src/events/balancer.py
src/events/broker.py
src/events/tls.py
src/managers/config.py
tests/integration/test_balancer.py
tests/unit/test_tls.py

Based on [VM PR](https://github.com/canonical/kafka-operator/pull/220)

[DPE-4581] Port CC TLS

---

src/charm.py
src/events/zookeeper.py

See https://github.com/canonical/zookeeper-operator/pull/162 for rationale and explanations.

[DPE-5218] Enable compatibility with ZK restore feature

---

src/core/cluster.py
src/core/models.py
src/events/balancer.py
src/events/peer_cluster.py
src/literals.py
tests/integration/helpers.py
tests/integration/test_balancer.py
tests/integration/test_charm.py

Copy/paste from https://github.com/canonical/kafka-operator/pull/244

[DPE-5226] - refactor: make 'broker' the central relation 

---

src/events/broker.py

[DPE-5544] - fix: set dir permissions & remove lost+found on storageattached

---

src/core/structured_config.py
tests/unit/test_structured_config.py

Updates config values and constraints for Kafka 4.0 based on KIP-1030
-----------
Port from https://github.com/canonical/kafka-operator/pull/345

[DPE-7142] Update configs

---

docs/tutorial/introduction.inc

A quick fix for sudden duplication of the Tutorial nav menu item

docs: Hotfix for nav menu tutorial duplication

---

src/core/workload.py
src/events/broker.py
src/events/controller.py
src/literals.py
src/managers/config.py
src/managers/controller.py
tests/integration/helpers.py
tests/integration/test_charm.py
tests/integration/test_kraft.py
tests/unit/conftest.py
tests/unit/data/metadata_quorum_stub.py
tests/unit/test_charm.py
tests/unit/test_controller_manager.py

Syncs with https://github.com/canonical/kafka-operator/pull/375

[DPE-7657] feat: add broker_active check

---

docs/tutorial/integrate-with-client-applications.md

Delete duplicated content/sections in the tutorial.

Hotfix integrate app tutorial section duplicate

---

src/alert_rules/prometheus/kafka_metrics.rules
src/grafana_dashboards/kafka-metrics.json

Dashboard and alerts synced from https://github.com/canonical/kafka-operator/pull/394

Update monitoring for kafka 4
